***********************************************************************************************
* Programa CropSim
* Dados da simula  o
**********************************************************************************************
* Nome do arquivo meteorol gico
Pira_013.met

* Nome do arquivo da cultura
Milho.crp

* Dia Ordinal ("Juliano") do in cio da simula  o
32
***********************************************************************************************
* Fim do Arquivo